const TwAppsConst = {
  STORAGE_TOKEN: 'key',
  // STYLE_DARK_GRAY: '#bcbcbc',

  IMG_DIR_PATH: 'img',

  USER_INFO_ENDPOINT: '/user_info',
  MUTED_USERS_ENDPOINT: '/muted_list',
  UNMUTE_USER_ENDPOINT: '/unmute',
  MUTE_USER_ENDPOINT: '/mute',

  APPNAME_MUTER: 'MuteReminder',
  APPNAME_BLOCKER: 'BlockReminder',

  /*
    ==============================================
     アクション名
    ==============================================
  */
  ACTION_CHANGE_BASE_URL: 'CHANGE_BASE_URL',
  ACTION_CHANGE_ISMUTERMENU_OPENED: 'CHANGE_ISMUTERMENU_OPENED',
  ACTION_CHANGE_USER_INFO: 'CHANGE_USER_INFO',
  ACTION_CHANGE_MUTED_USERS: 'CHANGE_MUTED_USERS',
  ACTION_TOGGLE_MUTED: 'TOGGLE_MUTED',
  ACTION_CHANGE_MUTED: 'CHANGE_MUTED',
  ACTION_USER_REQUEST_START: 'USER_REQUEST_START',
  ACTION_USER_REQUEST_END: 'USER_REQUEST_END',
  ACTION_MUTE_REQUEST_START: 'MUTE_REQUEST_START',
  ACTION_MUTE_REQUEST_END: 'MUTE_REQUEST_END',
  ACTION_CHANGE_ERR_MESSAGE: 'CHANG_ERR_MESSAGE',
  ACTION_CHANGE_POPUP_MESSAGE: 'CHANGE_POPUP_MESSAGE',


  HEADER_MENU_INITIAL: 'initial',
  HEADER_MENU_CLOSED: 'closed',
  HEADER_MENU_OPENED: 'opened',
  SHOW_TWEETS_INITIAL: 'initial',
  SHOW_TWEETS_CLOSED: 'closed',
  SHOW_TWEETS_OPENED: 'opened',
  REQUEST_STATUS_COMPLETE: 'complete',
  REQUEST_STATUS_LOADING: 'loading',
} as const;

export default TwAppsConst;
